name: Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Setup environment variables
      env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS: ${{ secrets.DB_PASS }}
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
      run: |
        echo "DB_USER=$DB_USER" >> .env.test
        echo "DB_PASS=$DB_PASS" >> .env.test
        echo "DB_HOST=$DB_HOST" >> .env.test
        echo "DB_PORT=$DB_PORT" >> .env.test
        echo "DB_NAME=$DB_NAME" >> .env.test

    - name: Run Mocha tests
      run: npm test
